# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services.hermes_pb2 as hermes__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hermes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HermesTenancyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateTenantKey = channel.unary_unary(
                '/hermes.HermesTenancyService/ValidateTenantKey',
                request_serializer=hermes__pb2.TenantKeyRequest.SerializeToString,
                response_deserializer=hermes__pb2.TenantKeyResponse.FromString,
                _registered_method=True)
        self.GetExposureLimits = channel.unary_unary(
                '/hermes.HermesTenancyService/GetExposureLimits',
                request_serializer=hermes__pb2.ExposureLimitsRequest.SerializeToString,
                response_deserializer=hermes__pb2.ExposureLimitsResponse.FromString,
                _registered_method=True)
        self.ReportTenantStatus = channel.unary_unary(
                '/hermes.HermesTenancyService/ReportTenantStatus',
                request_serializer=hermes__pb2.TenantStatusRequest.SerializeToString,
                response_deserializer=hermes__pb2.TenantStatusResponse.FromString,
                _registered_method=True)


class HermesTenancyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateTenantKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExposureLimits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTenantStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HermesTenancyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateTenantKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTenantKey,
                    request_deserializer=hermes__pb2.TenantKeyRequest.FromString,
                    response_serializer=hermes__pb2.TenantKeyResponse.SerializeToString,
            ),
            'GetExposureLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExposureLimits,
                    request_deserializer=hermes__pb2.ExposureLimitsRequest.FromString,
                    response_serializer=hermes__pb2.ExposureLimitsResponse.SerializeToString,
            ),
            'ReportTenantStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTenantStatus,
                    request_deserializer=hermes__pb2.TenantStatusRequest.FromString,
                    response_serializer=hermes__pb2.TenantStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hermes.HermesTenancyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hermes.HermesTenancyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HermesTenancyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateTenantKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.HermesTenancyService/ValidateTenantKey',
            hermes__pb2.TenantKeyRequest.SerializeToString,
            hermes__pb2.TenantKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExposureLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.HermesTenancyService/GetExposureLimits',
            hermes__pb2.ExposureLimitsRequest.SerializeToString,
            hermes__pb2.ExposureLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTenantStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hermes.HermesTenancyService/ReportTenantStatus',
            hermes__pb2.TenantStatusRequest.SerializeToString,
            hermes__pb2.TenantStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
