# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hermes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hermes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chermes.proto\x12\x06hermes\"6\n\x10TenantKeyRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t\"<\n\x11TenantKeyResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"*\n\x15\x45xposureLimitsRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\"f\n\x16\x45xposureLimitsResponse\x12\x18\n\x10max_exposure_usd\x18\x01 \x01(\x01\x12\x14\n\x0cmax_leverage\x18\x02 \x01(\x05\x12\x1c\n\x14\x61llowed_symbol_regex\x18\x03 \x01(\t\"q\n\x13TenantStatusRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x12\n\nstatus_str\x18\x02 \x01(\t\x12\x17\n\x0f\x63urrent_pnl_usd\x18\x03 \x01(\x01\x12\x1a\n\x12\x63urrent_margin_usd\x18\x04 \x01(\x01\"A\n\x14TenantStatusResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x13\n\x0binstruction\x18\x02 \x01(\t2\x85\x02\n\x14HermesTenancyService\x12H\n\x11ValidateTenantKey\x12\x18.hermes.TenantKeyRequest\x1a\x19.hermes.TenantKeyResponse\x12R\n\x11GetExposureLimits\x12\x1d.hermes.ExposureLimitsRequest\x1a\x1e.hermes.ExposureLimitsResponse\x12O\n\x12ReportTenantStatus\x12\x1b.hermes.TenantStatusRequest\x1a\x1c.hermes.TenantStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hermes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENANTKEYREQUEST']._serialized_start=24
  _globals['_TENANTKEYREQUEST']._serialized_end=78
  _globals['_TENANTKEYRESPONSE']._serialized_start=80
  _globals['_TENANTKEYRESPONSE']._serialized_end=140
  _globals['_EXPOSURELIMITSREQUEST']._serialized_start=142
  _globals['_EXPOSURELIMITSREQUEST']._serialized_end=184
  _globals['_EXPOSURELIMITSRESPONSE']._serialized_start=186
  _globals['_EXPOSURELIMITSRESPONSE']._serialized_end=288
  _globals['_TENANTSTATUSREQUEST']._serialized_start=290
  _globals['_TENANTSTATUSREQUEST']._serialized_end=403
  _globals['_TENANTSTATUSRESPONSE']._serialized_start=405
  _globals['_TENANTSTATUSRESPONSE']._serialized_end=470
  _globals['_HERMESTENANCYSERVICE']._serialized_start=473
  _globals['_HERMESTENANCYSERVICE']._serialized_end=734
# @@protoc_insertion_point(module_scope)
